# Generated by Django 3.1.3 on 2022-01-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0009_cricket_cricketapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('followedby', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=250)),
                ('tweetedby', models.CharField(max_length=5)),
                ('tweetedon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('userfullname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('useremail', models.CharField(max_length=50)),
                ('usern_mobile_no', models.CharField(max_length=13)),
                ('birthday', models.TimeField()),
            ],
        ),
    ]
