# Generated by Django 3.1.3 on 2022-01-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0010_following_tweet_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(),
        ),
    ]
