# Generated by Django 3.1.3 on 2022-01-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0011_auto_20220129_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birthday',
        ),
    ]
