# Generated by Django 3.1.3 on 2022-01-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0012_remove_users_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
