# Generated by Django 3.1.3 on 2022-01-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0013_auto_20220129_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetedon',
            field=models.IntegerField(),
        ),
    ]
