# Generated by Django 3.2.10 on 2022-01-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0015_auto_20220130_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='img',
            field=models.ImageField(default=None, upload_to='listtodo/static/img'),
            preserve_default=False,
        ),
    ]
